### ISSUE TITLE
Dark mode footer not working

### ISSUE THREAD

**Issue by Wulfheart** [confetti-framework/docs#20]
Firefox 86.0.1
Manjaro Linux

![image](https://user-images.githubusercontent.com/25671390/112699589-7554f600-8e8c-11eb-9d3c-977c9e48a25f.png)

**Comment by reindert-vetter** [comment]
@Wulfheart Thanks for your issue. I'm going to fix it soon. Difficult: styling is on the body, yet the body does not completely cover the page.

**Comment by Wulfheart** [comment]
I normally do a min-h-screen on the body element.

**Comment by reindert-vetter** [comment]
@Wulfheart Thanks! That is the same as `min-height: 100vh;`. 👍
